import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Florian Desmet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>Florian Desmet Blog</header>
        <main>{children}</main>
      </body>
      <footer>Footer</footer>
    </html>
  );
}
